Develop
mhamidjamil/orangePi pull request #21
Opened 2023-10-27 17:49 UTC by mhamidjamil

Orange pi can now communicate with TTGO TCall module.
it ill reply if ttgo tcall ask for time

2023-10-27 18:06 UTC, wasey-rao requested changes
Please resolve comments then ping me for approval.

2023-10-27 18:06 UTC, wasey-rao commented on serial_communication/web/app.py
> +def read_serial_data(data):
Please write a separate file for input management.

2023-10-27 18:06 UTC, wasey-rao commented on serial_communication/web/app.py
> +def fetch_current_time_online():
Don't use fetch_time....py code here, do it in separate file just call it form this code.

2023-10-27 18:06 UTC, wasey-rao commented on serial_communication/web/templates/index.html
> -                    serialData.innerText += data.data + '\n';
I don't think you input data is visible in web terminal, fix it.

2023-11-01 17:23 UTC, mhamidjamil commented on serial_communication/namaz/time_fetcher.py
if it is Isha time it don't show the coming Fajir time.

2023-11-01 18:02 UTC, wasey-rao approved these changes

2023-11-01 18:04 UTC, wasey-rao commented
I'm merging this code just because of Namaz time file, other wise kindly resolve comments before applying any changes in PR or you better create new PR for new feature.

2023-11-01 18:04 UTC, merged